Repository peerplays-network/peerplaysjs-ws, pull requests merged in 2019-04, with the labels that each got.

#9 PJL-20-ws: commitlint, commitizen, husky, standard-release, conventional-changelog.
  .huskyrc.json
  CHANGELOG.md
  README.md
  commitlint.config.js
  package-lock.json
  package.json
Labels: task

#8 RC-12-13
  build/peerplaysjs-ws.js
  build/peerplaysjs-ws.min.js
  dist/index.js
  dist/src/ConnectionManager.js
  lib/index.js
  lib/src/ConnectionManager.js
  test/Manager.js
Labels: release candidate

#14 added export for ChainWebSocket
  build/peerplaysjs-ws.js
  build/peerplaysjs-ws.min.js
  dist/index.js
  dist/src/ConnectionManager.js
  lib/index.js
  lib/src/ConnectionManager.js
Labels: bug

#15 Pbsa develop
  build/peerplaysjs-ws.js
  build/peerplaysjs-ws.min.js
  dist/index.js
  dist/src/ConnectionManager.js
  lib/index.js
  lib/src/ConnectionManager.js
Labels: task

#17 docs(readme): deprecated notice
  README.md
Labels: task

#18 Pbsa develop
  README.md
Labels: task

#19 Develop
  README.md
Labels: task
